image: python:3.7

variables:
    GIT_SUBMODULE_STRATEGY: recursive

unittest:
    stage: test
    script:
        - python -V
        - apt-get update
        - apt-get install libusb-1.0-0 fpga-icestorm -y
        - pip install -r requirements.txt
        - python -m unittest discover -v
