image: python:3.7

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    PYTHONPATH: /usr/share/fpga-icestorm/python/

unittest:
    stage: test
    script:
        - python -V
        - apt-get update
        - apt-get install -y --no-install-recommends libusb-1.0-0 fpga-icestorm
        - pip install -r requirements.txt
        - python -m unittest discover -v
